server:
    port: 8090
    servlet:
        context-path: /wholesale
spring:
    accountService:
        pageSize: 50
    application:
        name: wholesale-app
    datasource:
        url: jdbc:postgresql://localhost:5432/wholesale
        username: wholesale
        password: wholesale
        driver-class-name: org.postgresql.Driver
    flyway:
        locations: classpath:db/migration
        baseline-on-migrate: true
        enabled: true
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc:
                    lob:
                        non_contextual_creation: true
                temp:
                    use_jdbc_metadata_defaults: false
        show-sql: true
toggle:
    accountLists:
        1.enabled: true
    transactionLists:
        1.enabled: true
